### ISSUE TITLE
Integration with Powermock Runner Delegator

### ISSUE THREAD

**Issue by xeviknal** [bechte/junit-hierarchicalcontextrunner#22]
Hi all,

due to a legacy untestable code, I gotta use a Powermock. I don't want to let your Runner apart, so I found out that PowerMock could work with a `PowerMockRunnerDelegate` in order to combine both runners.
The surprise was that doesn't work. I'll paste you below part of the exception:

``` java
org/junit/internal/runners/rules/RuleFieldValidator
java.lang.NoClassDefFoundError: org/junit/internal/runners/rules/RuleFieldValidator
    at de.bechte.junit.runners.validation.RuleValidator.<clinit>(RuleValidator.java:14)
    at de.bechte.junit.runners.context.HierarchicalContextRunner.getValidator(HierarchicalContextRunner.java:79)
    at de.bechte.junit.runners.context.HierarchicalContextRunner.validate(HierarchicalContextRunner.java:64)
    at de.bechte.junit.runners.context.HierarchicalContextRunner.<init>(HierarchicalContextRunner.java:58)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    at org.powermock.reflect.internal.WhiteboxImpl.createInstance(WhiteboxImpl.java:1428)
    at org.powermock.reflect.internal.WhiteboxImpl.invokeConstructor(WhiteboxImpl.java:1301)
    at org.powermock.reflect.Whitebox.invokeConstructor(Whitebox.java:497)
    at org.powermock.modules.junit4.internal.impl.DelegatingPowerMockRunner$1.call(DelegatingPowerMockRunner.java:96)
```

From the current test implementation:

``` java
@RunWith(PowerMockRunner.class)
@PowerMockRunnerDelegate(HierarchicalContextRunner.class)
@PrepareForTest({Login.class})
public class LoginViaPasswordSpec extends SpecHelper {
...

}
```

Any hint/idea/approach to face that? I don't want to remove this runner... rspec is too deep in my mind.

Thanks in advanced,

**Comment by bechte** [comment]
Hi. It looks PowerMock is using a built in JUnit version? I didn't have a detail look into that issue, but it really seems like a class loading problem that might be the result of using a different (earlier) JUnit version.
